---
title: Preprocess MPsizeBase
author: Ian Hough
bibliography: ../references.bib
csl: ../apa-7th.csl
---

In [1]:
import os

import numpy as np
import pandas as pd

from utils import PROCESSED_DIR

# Directory containing MPsizeBase
DATA_DIR = "data/original"

# Overwrite outputs
OVERWRITE = True


def get_atmospheric_studies(mpsb: pd.DataFrame) -> pd.DataFrame:
    """Return studies of atmospheric microplastics"""

    mpsb = mpsb.loc[
        mpsb["sample_type"].eq("Atmosphere")
        # Exclude peat archive samples (unclear timeframe)
        & mpsb["sub_type1"].isin(
            ["Aerosol", "Total deposition", "Dry deposition", "Wet deposition"]
        )
    ].reset_index(drop=True)

    # Harmonize sub_type2
    mpsb["sub_type2"] = (
        mpsb["sub_type2"].replace("Rural", "Outdoor").replace("Urban", "Outdoor")
    )

    return mpsb


def load_mpsizebase(path: str) -> pd.DataFrame:
    """Load MPsizeBase"""

    # Load
    mpsb = pd.read_excel(path, sheet_name="Literature PSD data", header=2)
    mpsb.columns = mpsb.columns.str.lower()
    mpsb = mpsb.loc[mpsb["link"].notna()]  # skip any blank rows

    # Parse DOI from "link" column
    mpsb["doi"] = (
        mpsb["link"].str.strip().str.replace(r"^https?://doi.org/", "", regex=True)
    )

    # Merge "study" and "year" columns
    mpsb["study"] = mpsb["study"].apply(lambda x: x.split(" ")[0])
    mpsb["study"] = mpsb["study"] + mpsb["year"].astype(str)

    # Subset and rename columns
    # fmt: off
    cols = [
        "study", "doi", "lat", "lon", "alt", "sample_type", "sub_type1", "sub_type2",
        "psd_id", "mp_shape", "mp_density", "low_size", "high_size","cum_sum",
        "cum_sum_units", "filtered_low_size", "filtered_high_size", "filtered_cum_sum",
        "cumsum_slope", "cumsum_log_intercept", "cumsum_powerlaw_alpha",
        "cumsum_powerlaw_scale", "shape_factor", "comment"
    ]
    # fmt: on
    mpsb = (
        mpsb[cols]
        .rename(
            columns=lambda x: (
                x.removeprefix("mp_").removeprefix("cumsum_").removeprefix("powerlaw_")
            )
        )
        .rename(columns={"filtered_low_size": "lod_min", "filtered_high_size": "lod_max"})
    )

    return mpsb


def merge_wet_dry_deposition(data: pd.DataFrame) -> pd.DataFrame:
    """Merge colocated wet and dry deposition giving total deposition"""

    def merge_psd_ids(x: pd.Series) -> str:
        """Merge two PSD IDs e.g. Bra20_A_1 + Bra20_B_1 -> Bra20_AB_1"""

        letters = "".join(sorted(set(x.str[6])))
        psd_id = x.replace(f"_[{letters}]_", f"_{letters}_", regex=True).unique()[0]
        return psd_id

    def fit_powerlaw(x: pd.DataFrame) -> pd.Series:
        """Fit a powerlaw to log-transformed low size and cumulative counts

        Derivation [NOTE: MPsizeBase records alpha < 0]:
                  n(x) = C * x^alpha
            N(X>=xmin) = Integral[C * x^alpha] dx
                       = -C / (alpha + 1) * xmin^(alpha + 1)
                log(N) = log[-C / (alpha + 1)] + (alpha + 1) * log(xmin)
                       = intercept + slope * log(xmin)
                 alpha = slope - 1
                     C = -exp(intercept) * (alpha + 1)
        """

        # Fit slope and regression to log-transformed data
        x_log = np.log10(x["low_size"])
        y_log = np.log10(x["cum_sum"])
        slope, log_intercept = np.polyfit(x_log, y_log, deg=1)

        # Compute powerlaw parameters 'alpha' and 'scale'
        alpha = slope - 1
        scale = -(10**log_intercept) * (alpha + 1)

        return pd.Series(
            {
                "slope": slope,
                "log_intercept": log_intercept,
                "alpha": alpha,
                "scale": scale,
            }
        )

    # Sum co-located wet + dry deposition in matching size bins -> total deposition
    data = (
        data.loc[data["sub_type1"].isin(["Dry deposition", "Wet deposition"])]
        .groupby(
            ["study", "doi", "lat", "lon", "sub_type2", "shape", "low_size", "high_size"],
            as_index=False,
            sort=False,
        )
        .agg(
            psd_id=("psd_id", merge_psd_ids),
            lod_min=("lod_min", "min"),
            lod_max=("lod_max", "max"),
            density=("density", "first"),
            shape_factor=("shape_factor", "first"),
            cum_sum=("cum_sum", "sum"),
            n_counts=("cum_sum", "count"),
            n_unfiltered=("filtered_cum_sum", "count"),
        )
        .assign(sub_type1="Total deposition")
    )

    # Sanity check: ensure all size bins had counts for both wet and dry deposition
    if data["n_counts"].ne(2).any():
        raise ValueError("All size bins must have counts for both wet and dry deposition")

    # Fit powerlaw to each cumulative particle size distribution, using only size bins
    # that MPsizeBase used to fit powerlaw for both wet and dry deposition.
    params = (
        data.loc[data["n_unfiltered"].eq(2)]
        .groupby(["study", "doi", "psd_id"], sort=False)
        .apply(fit_powerlaw, include_groups=False)
    )

    # Collapse data to one row per observation and add columns with powerlaw parameters
    data = summarize_mpsb(data).join(params, on=params.index.names)

    return data


def prepare_mpsizebase(
    mpsb_date: str,
    out_name: str,
    mpsb_dir: str = DATA_DIR,
    out_dir: str = PROCESSED_DIR,
    overwrite: bool = False,
) -> pd.DataFrame:
    """Preprocess MPsizeBase data"""

    out_path = os.path.join(out_dir, out_name)
    if os.path.exists(out_path) and not overwrite:
        print(f"File exists: {out_path}")
        return pd.read_csv(out_path)

    # Load data
    date = pd.to_datetime(mpsb_date)
    mpsb_path = os.path.join(mpsb_dir, f"MPsizeBase v{date:%-d-%-m-%Y}.xlsx")
    mpsb = load_mpsizebase(mpsb_path)

    # Select only studies of atmospheric microplastic concentration or deposition
    mpsb = get_atmospheric_studies(mpsb)

    # Compute total deposition from Brahney2020's colocated measures of wet + dry
    # deposition and refit powerlaw
    brahney = mpsb.loc[mpsb["doi"].eq("10.1126/science.aaz5819")]
    brahney = merge_wet_dry_deposition(brahney)

    # Summarize size range and powerlaw parameters for each observation
    mpsb = summarize_mpsb(
        mpsb.loc[mpsb["sub_type1"].isin(["Aerosol", "Total deposition"])]
    )

    # Combine with total deposition of Brahney2020
    mpsb = (
        pd.concat([mpsb, brahney])
        .sort_values(["study", "doi", "psd_id"])
        .reset_index(drop=True)
    )

    # Identify unique particle size distributions
    mpsb.insert(
        loc=mpsb.columns.get_loc("psd_id"),
        column="psd",
        value=mpsb["psd_id"].replace(r"_\d+$", "", regex=True),
    )

    # Save as CSV
    mpsb.to_csv(out_path, index=False)
    print(f"-> {out_path}")

    return mpsb


def summarize_mpsb(data: pd.DataFrame) -> pd.DataFrame:
    """Return study, location, size range, and powerlaw parameters for each PSD"""

    # fmt: off
    group_cols = [
        "study", "doi", "lat", "lon", "sub_type1", "sub_type2", "psd_id", "shape"
    ]
    # fmt: on
    aggs = {
        "low_size": "min",
        "high_size": "max",
        "lod_min": "min",
        "lod_max": "max",
        "density": "first",
        "shape_factor": "first",
        "slope": "first",
        "log_intercept": "first",
        "alpha": "first",
        "scale": "first",
    }
    aggs = {k: v for k, v in aggs.items() if k in data}

    smry = data.groupby(group_cols, as_index=False, sort=False).agg(aggs)

    return smry

Introduction
------------

This notebook processes data from MPsizeBase and computes a typical size distribution for atmospheric microplastics.

[MPsizeBase](https://doi.org/10.5281/zenodo.20832480) [@Sonke2026; @Segur2026] is a large database of size-resolved environmental microplastic observations collected from the literature. It reports the parameters of a power law that best fit each observation's particle size distribution. We compute the median value of the parameter $\alpha$, which describes the relative frequency of small vs. large particles.

Preprocess MPsizeBase
---------------------

Most studies measured aerosols or total deposition. However, one study (@Brahney2020) simultaneously measured wet and dry deposition and reported them separately. To make the data comparable with other studies, we combine the wet and dry deposition counts to get total deposition and re-fit the parameters of the power law size distribution.

In [2]:
mpsb_date = "2026-05-19"

mpsb = prepare_mpsizebase(
    mpsb_dir=DATA_DIR,
    mpsb_date=mpsb_date,
    out_name=f"mpsizebase_atmo_{mpsb_date}.csv",
    overwrite=OVERWRITE,
)

-> data/processed/mpsizebase_atmo_2026-05-19.csv

Summary
-------

We compute summary statistics (mean, standard deviation, median, min, max) for the power law $\alpha$ parameter (exponent) across all observations in MPsizeBase, grouping observations by sample type (aerosol vs. total deposition) and microplastic shape (fibers vs. fragments).

Giving equal weight to each observation (note that some studies use a single aggregate PSD for all observations):

In [3]:
def q25(x: pd.Series) -> float:
    return x.quantile(0.25)


def q75(x: pd.Series) -> float:
    return x.quantile(0.75)


# Summarize for reference
# Aggregate over observations by sample type and shape
(
    mpsb.groupby(["shape", "sub_type1"])
    .agg(
        {
            "doi": "nunique",
            "psd": "nunique",
            "psd_id": "nunique",
            "alpha": ["mean", "std", "median", q25, q75, "min", "max"],
        }
    )
    .rename(columns={"psd_id": "obs"})
    .round(1)
)

                               doi     psd     obs alpha                   \
                           nunique nunique nunique  mean  std median  q25
shape     sub_type1
Fibers    Aerosol                8       9      11  -1.9  0.4   -1.7 -2.1
          Total deposition       9       9      19  -2.2  0.3   -2.2 -2.3
Films     Total deposition       2       2       2  -2.3  0.8   -2.3 -2.6
Fragments Aerosol               12      14      22  -2.4  0.8   -2.3 -2.8
          Total deposition       7      12      22  -2.4  0.3   -2.4 -2.4


                            q75  min  max
shape     sub_type1
Fibers    Aerosol          -1.6 -2.5 -1.4
          Total deposition -2.0 -2.8 -1.6
Films     Total deposition -2.0 -2.8 -1.7
Fragments Aerosol          -1.9 -4.5 -1.7
          Total deposition -2.4 -3.6 -2.0

Giving equal weight to each unique PSD:

In [4]:
# Summarize for reference
# Aggregate over PSDs by sample type and shape
(
    mpsb.groupby(["shape", "sub_type1", "doi", "psd"], as_index=False)[
        ["low_size", "high_size", "lod_min", "lod_max", "alpha"]
    ]
    .mean()
    .groupby(["shape", "sub_type1"])
    .agg(
        {
            "doi": "nunique",
            "psd": "nunique",
            "alpha": ["mean", "std", "median", q25, q75, "min", "max"],
        }
    )
    .round(1)
)

                               doi     psd alpha                             \
                           nunique nunique  mean  std median  q25  q75  min
shape     sub_type1
Fibers    Aerosol                8       9  -1.9  0.4   -1.7 -2.3 -1.6 -2.5
          Total deposition       9       9  -2.3  0.4   -2.2 -2.4 -2.1 -2.8
Films     Total deposition       2       2  -2.3  0.8   -2.3 -2.6 -2.0 -2.8
Fragments Aerosol               12      14  -2.7  0.9   -2.5 -3.3 -2.0 -4.5
          Total deposition       7      12  -2.5  0.5   -2.4 -2.5 -2.2 -3.6


                            max
shape     sub_type1
Fibers    Aerosol          -1.4
          Total deposition -1.6
Films     Total deposition -1.7
Fragments Aerosol          -1.7
          Total deposition -2.0

Giving equal weight to each study (take mean for studies that report multiple PSDs):

In [5]:
# Summarize for reference
# Aggregate over DOIs by sample type and shape
(
    mpsb.groupby(["shape", "sub_type1", "doi"], as_index=False)[
        ["low_size", "high_size", "lod_min", "lod_max", "alpha"]
    ]
    .mean()
    .groupby(["shape", "sub_type1"])
    .agg({"doi": "nunique", "alpha": ["mean", "std", "median", q25, q75, "min", "max"]})
    .round(1)
)

                               doi alpha
                           nunique  mean  std median  q25  q75  min  max
shape     sub_type1
Fibers    Aerosol                8  -1.9  0.4   -1.7 -2.2 -1.6 -2.5 -1.4
          Total deposition       9  -2.3  0.4   -2.2 -2.4 -2.1 -2.8 -1.6
Films     Total deposition       2  -2.3  0.8   -2.3 -2.6 -2.0 -2.8 -1.7
Fragments Aerosol               12  -2.8  0.9   -2.8 -3.4 -2.1 -4.5 -1.7
          Total deposition       7  -2.7  0.5   -2.4 -2.8 -2.4 -3.6 -2.2